name: Dacapo Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
      # Checkout MMTk OpenJDK - do this first so we can fetch metadata for OpenJDK repo
      - uses: actions/checkout@v2

      - name: Setup env vars
        run: |
          echo $PWD
          echo "OPENJDK_PATH=$PWD/openjdk" >> $GITHUB_ENV
          echo "BINDING_PATH=$PWD/mmtk-openjdk" >> $GITHUB_ENV
          echo "RUSTUP_TOOLCHAIN=`cat mmtk/rust-toolchain`" >> $GITHUB_ENV
          echo "OPENJDK_REPO=`sed -n 's/^openjdk_repo.=."\(.*\)"$/\1/p' < mmtk/Cargo.toml`" >> $GITHUB_ENV
          echo "OPENJDK_VERSION=`sed -n 's/^openjdk_version.=."\(.*\)"$/\1/p' < mmtk/Cargo.toml`" >> $GITHUB_ENV

      # Checkout OpenJDK
      - uses: actions/checkout@v2
        with:
          repository: $OPENJDK_REPO
          ref: $OPENJDK_VERSION
          path: $OPENJDK_PATH

      - name: Setup Environments
        run: ./.github/scripts/ci-setup.sh

      # Run the tests
      - name: Dacapo Tests
        run: ./.github/scripts/ci-test-normal.sh
      - name: DaCapo Tests for Global Allocation Bit
        run: ./.github/scripts/ci-test-global-alloc-bit.sh

      # Style check
      - name: Style checks
        run: ./.github/scripts/ci-style.sh
